<?php
// $Id$

/**
 * @file
 * Provides the basic Configuration for our melted Server
 *
 * This Module provides a Form for configuring our Melted Playout Server Instance
 * You can find more Information about melted on their sourceforge page
 * http://mltframework.org
 */

include(drupal_get_path('module', 'melted').'/inc/client.php');
include(drupal_get_path('module', 'melted').'/inc/playout.php');

/**
 * Implements hook_help().
 */
function melted_help($path, $arg) {
  if ($path == 'admin/help#melted') {
    return t('Configuration for the Melted Playout Server');
  }
}


/**
 * Implements hook_permission().
 *
 * Since we do not want all Users alter the Playout Settings
 */
function melted_permission() {
  return array(
    'access melted config' => array(
    'title' => t('Alter melted configuration'),
    'description' => t('Allow users to manage the Melted Server Configuration'),
    ),
    'access melted' => array(
    'title' => t('View the Data Melted provides'),
      'description' => t('Allow users to view the Data of Melted like playlists, controlbar etc.'),
    ),

  );
}


/** 
  * Implements hook_menu().
 */
function melted_menu() {
  $items['admin/config/melted'] = array(
    'title' => t('Melted Playout Server'),
    'description' => t('Configure several options fnd view the Status of the melted Playout Server'),
    'position' => 'right',
    'weight' => -9,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access melted config'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/melted/settings'] = array(
    'title' => t('Melted Settings'),
    'description' => t('Enter the Hostname and Port of the melted Playout Server'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('melted_admin_settings'),
    'access arguments' => array('access melted config'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'melted.admin.inc',
  );

  $items['melted/playlist'] = array(
    'title' => t('Watch Playlist'),
    'page callback' => 'melted_playlist',
    'access arguments' => array('access melted'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  //now define the menu entry for the status block callback. so we can make some nice ajax
  $items['melted/refresh'] = array(
    'page callback' => 'melted_refresh',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implementation of hook_block_info
 */
function melted_block_info() {
  $blocks = array();
  $blocks['melted_control'] = array(
    'info' => t('Shows the Status of the Melted Server'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


 /**
  * Implementation of hook_block_view
  */
function melted_block_view($block_name = '') {
  if ($block_name = 'melted_control') {
    //include_once('includes/playout.php');
    //include_once('includes/client.php'); 
//    $content = melted_getstatus(); 

  $path = drupal_get_path('module', 'melted');
  drupal_add_js ($path . '/js/melted.js');
  $content = "<div class='melted_status'></div>"; //melted_ajax();
//$content = melted_refresh();
    $block = array(
      'subject' => t('Melted Status'),
      'content' => $content,
    );
//drupal_set_message(print dpm($playout->Mvcp->status()),'status');  
    return $block;
  }
}




function melted_refresh() {
  $settings = array(
    'host' => variable_get('melted_server_config_ip'),
    'port' => variable_get('melted_server_config_port'),
    'mode' => 1,
  );
  $playlist = array();
  $playout = new Playout($settings,$playlist);
  $output = '<div id="melted_status">';
  if ($playout->connect()) {
    $status = $playout->Mvcp->status();
    $output.= "<p>Connected to Melted</p>";
    $output.= "<p>Status:".$status['mode']."</p>";
    $output.= "<p>Clip:".$status['currentClip']."</p";
    $output.= "<p>Frame:".$status['currentFrame']."/".$status['length']."</p>";

  }
  else {
    $output.="not connected";
  }
  $output.="</div>";
 //return $output; 
// drupal_set_message(print dpm($_POST),'status');
// if (!empty($_POST['js'])) {
   drupal_json_output(array ('data' => $output));
/* } else
 {
   return $output;
 }*/
}



function melted_playlist() {
  $settings = array(
    'host' => variable_get('melted_server_config_ip'),
    'port' => variable_get('melted_server_config_port'),
    'mode' => 1,
  );
  $playlist = array();
  $playout = new Playout($settings,$playlist);
  $rows = $playout->Mvcp->listClips();
 // drupal_set_message(print dpm($listClips),'status');
  $header = array('index', 'file', 'in', 'out', 'realLength', 'estimatedLength');
  return theme('table', array('header' => $header, 'rows' => $rows,)); //listClips[0]['file'];//theme_table($header, $listClips); //dpm($status); 
}
